### ISSUE TITLE
You should fix it on Nextjs documentation

### ISSUE THREAD

**Issue by jsellam** [livekit/livekit-docs#26]
Hi, to start, thank you for all your work, I'm starting to migrate from janus to livekit and you have done a very good job.
I'm starting a little project in nextjs to try the js and nodejs sdk and I have seen errors on documentations : 

- You use NEXT_PUBLIC_LIVEKIT_URL in the room page but the value is missing in the .env.development.local file 
- In the room page, the useEffect don't have dependencies and the api is call on each render (many times by second)
You should change to : 
```
 useEffect(() => {
    (async () => {
      const resp = await fetch(`/api/get_lk_token?room=${room}&username=${name}`);
      const data = await resp.json();
      setToken(data.token);
    })();
  },[]); <---- add an empty array as second parameter.
```

thank you,
Jérémie.

**Comment by davidzhao** [comment]
thank you for pointing these out! we'll fix them right away.
